# Derived IPA server configuration
ipa_realm: '{{ ipa_domain | upper }}'

# Derived DNS reverse zone for LDAP server
ldap_revzone: "{{ ldap_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\3.\\2.\\1.in-addr.arpa') }}"
ldap_ptrname: "{{ ldap_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\4') }}"

# Derived DNS reverse zone for client machine
client_revzone: "{{ client_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\3.\\2.\\1.in-addr.arpa') }}"
client_ptrname: "{{ client_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\4') }}"

# Derived DNS reverse zone for AD machine
ad_revzone: "{{ ad_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\3.\\2.\\1.in-addr.arpa') }}"
ad_ptrname: "{{ ad_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\4') }}"
ad_child_revzone: "{{ ad_child_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\3.\\2.\\1.in-addr.arpa') }}"
ad_child_ptrname: "{{ ad_child_ip | regex_replace('^(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)$', '\\4') }}"
