- name: 'Create new AD forest {{ ad_domain }}'
  win_shell: |
    Import-Module ADDSDeployment

    Install-ADDSForest                                                        \
      -DomainName "{{ ad_domain }}"                                           \
      -CreateDnsDelegation:$false                                             \
      -DomainNetbiosName "{{ ad_netbios }}"                                   \
      -ForestMode "{{ forest_mode }}"                                         \
      -DomainMode "{{ domain_mode }}"                                         \
      -Force:$true                                                            \
      -InstallDns:$true                                                       \
      -NoRebootOnCompletion:$true                                             \
      -SafeModeAdministratorPassword                                          \
        (ConvertTo-SecureString '{{ ad_safe_password }}' -AsPlainText -Force)
  args:
    creates: 'C:\Windows\NTDS'
