- name: Install SSSD build and run-time dependencies
  become: True
  package:
    name: '{{ item }}'
    state: present
  when: skip_packages is not defined or not skip_packages
  with_items:
  - adcli
  - augeas-devel
  - autoconf
  - automake
  - bind-utils
  - c-ares-devel
  - check
  - check-devel
  - cifs-utils-devel
  - dbus-devel
  - dbus-libs
  - diffstat
  - docbook-style-xsl
  - doxygen
  - freeipa-client
  - gettext
  - gettext-devel
  - glib2-devel
  - http-parser-devel
  - jansson-devel
  - keyutils-libs-devel
  - krb5-devel
  - libcmocka
  - libcmocka-devel
  - libcollection-devel
  - libcurl-devel
  - libdhash-devel
  - libini_config-devel
  - libldb
  - libldb-devel
  - libnfsidmap-devel
  - libnl3-devel
  - libpath_utils-devel
  - libref_array-devel
  - libselinux-devel
  - libsemanage-devel
  - libsmbclient-devel
  - libtalloc
  - libtalloc-devel
  - libtdb
  - libtdb-devel
  - libtevent
  - libtevent-devel
  - libtool
  - libuuid-devel
  - libxml2
  - libxslt
  - m4
  - nspr-devel
  - nss-devel
  - nss-util-devel
  - nss_wrapper
  - oddjob
  - oddjob-mkhomedir
  - openldap-devel
  - pam-devel
  - pam_wrapper
  - pcre-devel
  - pkgconfig
  - po4a
  - popt-devel
  - python-devel
  - python3-devel
  - realmd
  - resolv_wrapper
  - samba-common-tools
  - samba-devel
  - samba4-devel
  - selinux-policy-targeted
  - socket_wrapper
  - sssd
  - sssd-*
  - systemd-devel
  - systemtap-sdt-devel
  - uid_wrapper
  
- name: Install debug information
  become: True
  shell: |
    dnf debuginfo-install -y        \
        dbus-devel                  \
        libcmocka                   \
        libcollection-devel         \
        libdhash                    \
        libini_config               \
        libldb                      \
        libtalloc                   \
        libtevent
  when: skip_packages is not defined or not skip_packages
    
- name: Join IPA domain
  become: True
  shell: |
    /usr/sbin/ipa-client-install --unattended          \
      --domain {{ ipa_domain | quote }}                \
      --principal admin                                \
      --password 123456789                             \
      --force-ntpd
  register: installed
  args:
    creates: /etc/ipa/ca.crt
  when: dist is not defined or dist != "suse"  

- name: Copy IPA keytab to local folder
  become: True
  ignore_errors: yes
  copy:
    src: /etc/krb5.keytab
    dest: '/etc/sssd/ipa.keytab'
    remote_src: yes
  when: 
    - dist is not defined or dist != "suse"
    - installed.changed
  
- name: Remove /etc/krb5.keytab
  become: True
  file:
    path: /etc/krb5.keytab
    state: absent

- name: Copy IPA keytab to shared folder
  become: True
  ignore_errors: yes
  copy:
    force: True
    src: /etc/sssd/ipa.keytab
    dest: '/shared/enrollment/{{ inventory_hostname }}/ipa.keytab'
    remote_src: yes
  when: dist is not defined or dist != "suse"
    
    
- name: Join to Active Directory domain
  become: True
  shell: |
    echo vagrant | realm join {{ ad_domain | quote }}
    touch /etc/sssd/ad_enrolled
  register: installed
  args:
    creates: /etc/sssd/ad_enrolled
  when: dist is not defined or dist != "suse"

  # SUSE specific AD Join Steps
- name: Create /etc/krb5.conf (SUSE)
  become: True
  template:
    src: suse.krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0600
  register: installed
  when: dist == "suse"  

- name: Create /etc/samba/smb.conf (SUSE)
  become: True
  template:
    src: suse.smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0600
  register: installed
  when: dist == "suse"  

- name: Create /etc/nsswitch.conf (SUSE)
  become: True
  template:
    src: suse.nsswitch.conf
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: 0600
  register: installed
  when: dist == "suse" 

- name: Authenticate on the target domain using Kerberos (SUSE)
  become: True
  shell: |
    echo vagrant | kinit Administrator
    touch /etc/sssd/kinit_enrolled
  register: installed
  args:
    creates: /etc/sssd/kinit_enrolled
  when: dist is defined or dist == "suse"

- name: Join to Active Directory domain using net command (SUSE)
  become: True
  shell: |
    net ads join osname=”SLES” osVersion=15 osServicePack=”Latest” --no-dns-updates -k 
    touch /etc/sssd/ad_suse_enrolled
  register: installed
  args:
    creates: /etc/sssd/ad_suse_enrolled
  when: dist is defined or dist == "suse"
  

- name: Copy AD keytab to local folder
  become: True
  copy:
    src: /etc/krb5.keytab
    dest: '/etc/sssd/ad.keytab'
    remote_src: yes
  when: installed.changed
  
- name: Remove /etc/krb5.keytab
  become: True
  file:
    path: /etc/krb5.keytab
    state: absent

- name: Copy AD keytab to shared folder
  become: True
  ignore_errors: yes
  copy:
    force: True
    src: /etc/sssd/ad.keytab
    dest: '/shared/enrollment/{{ inventory_hostname }}/ad.keytab'
    remote_src: yes

- name: Configure PAM to use sssd (SUSE)
  become: True
  shell: |
    pam-config -–add -–sss
    pam-config –-add –-mkhomedir 
    touch /etc/sssd/pam_configured
  register: installed
  args:
    creates: /etc/sssd/pam_configured
  when: dist is defined or dist == "suse"

- name: Create /etc/sssd/sssd.conf
  become: True
  template:
    src: sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  register: installed
  when: dist is not defined or dist != "suse"

- name: Create /etc/sssd/sssd.conf (SUSE)
  become: True
  template:
    src: suse.sssd.conf
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  register: installed
  when: dist == "suse"  

- name: Create /etc/sudo.conf
  become: True
  template:
    src: sudo.conf
    dest: /etc/sudo.conf
    owner: root
    group: root
    mode: 0644
    
- name: Restart SSSD
  become: True
  service:
    name: sssd.service
    enabled: yes
    state: restarted
  when: installed.changed
